export {
  MaskingKind,
  NormalizationKind,
  PaymentChannelAutomation,
  PaymentChannelGroup,
  PaymentFieldType,
  ValidationRuleKind,
  addPaymentChannelSchema,
  definePaymentChannelSchema,
  getPaymentChannelSchema,
  listPaymentChannelSchemas,
  maskFieldValue,
  normalizeFieldValue,
  renderDetailRows,
  validatePaymentChannelData,
  type CountryCode,
  type CurrencyCode,
  type DetailRow,
  type EvidenceField,
  type PaymentChannelField,
  type PaymentChannelId,
  type PaymentChannelSchema,
  type PaymentInstructions,
  type PaymentNetwork,
  type MoneyNetworkId,
  type RenderedDetailRow,
  type SelectOption,
  type ValidationIssue,
  type ValidationResult,
  type ValidationRule,
} from "./core.js";

import { buildPaymentChannelRegistry, type PaymentChannelSchema, type PaymentChannelId } from "./core.js";
import { builtinPaymentChannels } from "./channels/index.js";

export {
  airtelMoneyKeKesPaymentChannel,
  airtelMoneyMwMwkPaymentChannel,
  airtelMoneyTillMwMwkPaymentChannel,
  builtinPaymentChannels,
  cashAoAoaPaymentChannel,
  cashAuAudPaymentChannel,
  cashAsUsdPaymentChannel,
  cashBfXofPaymentChannel,
  cashBiBifPaymentChannel,
  cashBjXofPaymentChannel,
  cashBmBmdPaymentChannel,
  cashArArsPaymentChannel,
  cashBoBobPaymentChannel,
  cashBrBrlPaymentChannel,
  cashBwBwpPaymentChannel,
  cashCaCadPaymentChannel,
  cashCdCdfPaymentChannel,
  cashCfXafPaymentChannel,
  cashCgXafPaymentChannel,
  cashCiXofPaymentChannel,
  cashCkNzdPaymentChannel,
  cashClClpPaymentChannel,
  cashCmXafPaymentChannel,
  cashCoCopPaymentChannel,
  cashCvCvePaymentChannel,
  cashDjDjfPaymentChannel,
  cashDzDzdPaymentChannel,
  cashEcUsdPaymentChannel,
  cashEgEgpPaymentChannel,
  cashEhMadPaymentChannel,
  cashErErnPaymentChannel,
  cashEtEtbPaymentChannel,
  cashFjFjdPaymentChannel,
  cashFmUsdPaymentChannel,
  cashFkFkpPaymentChannel,
  cashGaXafPaymentChannel,
  cashGbGbpPaymentChannel,
  cashGfEurPaymentChannel,
  cashGhGhsPaymentChannel,
  cashGlDkkPaymentChannel,
  cashGmGmdPaymentChannel,
  cashGnGnfPaymentChannel,
  cashGqXafPaymentChannel,
  cashGuUsdPaymentChannel,
  cashGwXofPaymentChannel,
  cashGyGydPaymentChannel,
  cashInInrPaymentChannel,
  cashKeKesPaymentChannel,
  cashKiAudPaymentChannel,
  cashKmKmfPaymentChannel,
  cashLrLrdPaymentChannel,
  cashLrUsdPaymentChannel,
  cashLsLslPaymentChannel,
  cashLsZarPaymentChannel,
  cashLyLydPaymentChannel,
  cashMaMadPaymentChannel,
  cashMgMgaPaymentChannel,
  cashMhUsdPaymentChannel,
  cashMlXofPaymentChannel,
  cashMpUsdPaymentChannel,
  cashMrMruPaymentChannel,
  cashMuMurPaymentChannel,
  cashMwMwkPaymentChannel,
  cashMzMznPaymentChannel,
  cashNaNadPaymentChannel,
  cashNaZarPaymentChannel,
  cashNcXpfPaymentChannel,
  cashNfAudPaymentChannel,
  cashNeXofPaymentChannel,
  cashNgNgnPaymentChannel,
  cashNzNzdPaymentChannel,
  cashPkPkrPaymentChannel,
  cashPmEurPaymentChannel,
  cashPgPgkPaymentChannel,
  cashNrAudPaymentChannel,
  cashNuNzdPaymentChannel,
  cashPfXpfPaymentChannel,
  cashPnNzdPaymentChannel,
  cashPwUsdPaymentChannel,
  cashPePenPaymentChannel,
  cashPyPygPaymentChannel,
  cashReEurPaymentChannel,
  cashRwRwfPaymentChannel,
  cashSbSbdPaymentChannel,
  cashScScrPaymentChannel,
  cashSdSdgPaymentChannel,
  cashShShpPaymentChannel,
  cashSlSlePaymentChannel,
  cashSnXofPaymentChannel,
  cashSoSosPaymentChannel,
  cashSoUsdPaymentChannel,
  cashSrSrdPaymentChannel,
  cashSsSspPaymentChannel,
  cashStStnPaymentChannel,
  cashSzSzlPaymentChannel,
  cashSzZarPaymentChannel,
  cashTdXafPaymentChannel,
  cashTgXofPaymentChannel,
  cashTkNzdPaymentChannel,
  cashTnTndPaymentChannel,
  cashToTopPaymentChannel,
  cashTvAudPaymentChannel,
  cashTzTzsPaymentChannel,
  cashUgUgxPaymentChannel,
  cashVuVuvPaymentChannel,
  cashUsUsdPaymentChannel,
  cashWfXpfPaymentChannel,
  cashWsWstPaymentChannel,
  cashUyUyuPaymentChannel,
  cashVeVesPaymentChannel,
  cashYtEurPaymentChannel,
  cashZaZarPaymentChannel,
  cashZmZmwPaymentChannel,
  cashZwUsdPaymentChannel,
  cashZwZwgPaymentChannel,
  createCashPaymentChannel,
  mpesaPaybillKeKesPaymentChannel,
  mpesaPhoneKeKesPaymentChannel,
  mpesaPochiKeKesPaymentChannel,
  mpesaTillKeKesPaymentChannel,
  payshapAccountZaZarPaymentChannel,
  payshapShapidZaZarPaymentChannel,
  pesalinkAccountKeKesPaymentChannel,
  telebirrPhoneEtEtbPaymentChannel,
  tnmMpambaMerchantMwMwkPaymentChannel,
  tnmMpambaMwMwkPaymentChannel,
} from "./channels/index.js";

export function createPaymentChannelRegistry(
  schemas: readonly PaymentChannelSchema[] = builtinPaymentChannels,
): Map<PaymentChannelId, PaymentChannelSchema> {
  return buildPaymentChannelRegistry(schemas);
}
