export {
  MaskingKind,
  NormalizationKind,
  PaymentChannelAutomation,
  PaymentChannelGroup,
  PaymentFieldType,
  ValidationRuleKind,
  addPaymentChannelSchema,
  definePaymentChannelSchema,
  getPaymentChannelSchema,
  listPaymentChannelSchemas,
  maskFieldValue,
  normalizeFieldValue,
  renderDetailRows,
  validatePaymentChannelData,
  type CountryCode,
  type CurrencyCode,
  type DetailRow,
  type EvidenceField,
  type PaymentChannelField,
  type PaymentChannelId,
  type PaymentChannelSchema,
  type PaymentInstructions,
  type PaymentNetwork,
  type MoneyNetworkId,
  type RenderedDetailRow,
  type SelectOption,
  type ValidationIssue,
  type ValidationResult,
  type ValidationRule,
} from "./core.js";

import { buildPaymentChannelRegistry, type PaymentChannelSchema, type PaymentChannelId } from "./core.js";
import { builtinPaymentChannels } from "./channels/index.js";

export {
  airtelMoneyKeKesPaymentChannel,
  airtelMoneyMwMwkPaymentChannel,
  airtelMoneyTillMwMwkPaymentChannel,
  builtinPaymentChannels,
  cashAdEurPaymentChannel,
  cashAfAfnPaymentChannel,
  cashAgXcdPaymentChannel,
  cashAiXcdPaymentChannel,
  cashAlAllPaymentChannel,
  cashAoAoaPaymentChannel,
  cashArArsPaymentChannel,
  cashAsUsdPaymentChannel,
  cashAtEurPaymentChannel,
  cashAuAudPaymentChannel,
  cashAwAwgPaymentChannel,
  cashAxEurPaymentChannel,
  cashBaBamPaymentChannel,
  cashBbBbdPaymentChannel,
  cashBdBdtPaymentChannel,
  cashBeEurPaymentChannel,
  cashBfXofPaymentChannel,
  cashBgBgnPaymentChannel,
  cashBiBifPaymentChannel,
  cashBjXofPaymentChannel,
  cashBlEurPaymentChannel,
  cashBmBmdPaymentChannel,
  cashBnBndPaymentChannel,
  cashBoBobPaymentChannel,
  cashBqUsdPaymentChannel,
  cashBrBrlPaymentChannel,
  cashBsBsdPaymentChannel,
  cashBtBtnPaymentChannel,
  cashBwBwpPaymentChannel,
  cashByBynPaymentChannel,
  cashBzBzdPaymentChannel,
  cashCaCadPaymentChannel,
  cashCdCdfPaymentChannel,
  cashCfXafPaymentChannel,
  cashCgXafPaymentChannel,
  cashChChfPaymentChannel,
  cashCiXofPaymentChannel,
  cashCkNzdPaymentChannel,
  cashClClpPaymentChannel,
  cashCmXafPaymentChannel,
  cashCnCnyPaymentChannel,
  cashCoCopPaymentChannel,
  cashCrCrcPaymentChannel,
  cashCuCupPaymentChannel,
  cashCvCvePaymentChannel,
  cashCwAngPaymentChannel,
  cashCzCzkPaymentChannel,
  cashDeEurPaymentChannel,
  cashDkDkkPaymentChannel,
  cashDjDjfPaymentChannel,
  cashDmXcdPaymentChannel,
  cashDoDopPaymentChannel,
  cashDzDzdPaymentChannel,
  cashEcUsdPaymentChannel,
  cashEeEurPaymentChannel,
  cashEgEgpPaymentChannel,
  cashEhMadPaymentChannel,
  cashErErnPaymentChannel,
  cashEsEurPaymentChannel,
  cashEtEtbPaymentChannel,
  cashFiEurPaymentChannel,
  cashFjFjdPaymentChannel,
  cashFkFkpPaymentChannel,
  cashFmUsdPaymentChannel,
  cashFoDkkPaymentChannel,
  cashFrEurPaymentChannel,
  cashGaXafPaymentChannel,
  cashGbGbpPaymentChannel,
  cashGdXcdPaymentChannel,
  cashGfEurPaymentChannel,
  cashGgGbpPaymentChannel,
  cashGhGhsPaymentChannel,
  cashGiGipPaymentChannel,
  cashGlDkkPaymentChannel,
  cashGmGmdPaymentChannel,
  cashGnGnfPaymentChannel,
  cashGpEurPaymentChannel,
  cashGqXafPaymentChannel,
  cashGrEurPaymentChannel,
  cashGtGtqPaymentChannel,
  cashGuUsdPaymentChannel,
  cashGwXofPaymentChannel,
  cashGyGydPaymentChannel,
  cashHkHkdPaymentChannel,
  cashHnHnlPaymentChannel,
  cashHrEurPaymentChannel,
  cashHtHtgPaymentChannel,
  cashHuHufPaymentChannel,
  cashIdIdrPaymentChannel,
  cashIeEurPaymentChannel,
  cashImGbpPaymentChannel,
  cashInInrPaymentChannel,
  cashIrIrrPaymentChannel,
  cashIsIskPaymentChannel,
  cashItEurPaymentChannel,
  cashJeGbpPaymentChannel,
  cashJmJmdPaymentChannel,
  cashJpJpyPaymentChannel,
  cashKeKesPaymentChannel,
  cashKgKgsPaymentChannel,
  cashKhKhrPaymentChannel,
  cashKiAudPaymentChannel,
  cashKmKmfPaymentChannel,
  cashKnXcdPaymentChannel,
  cashKpKpwPaymentChannel,
  cashKrKrwPaymentChannel,
  cashKyKydPaymentChannel,
  cashKzKztPaymentChannel,
  cashLaLakPaymentChannel,
  cashLcXcdPaymentChannel,
  cashLiChfPaymentChannel,
  cashLkLkrPaymentChannel,
  cashLrLrdPaymentChannel,
  cashLrUsdPaymentChannel,
  cashLsLslPaymentChannel,
  cashLsZarPaymentChannel,
  cashLtEurPaymentChannel,
  cashLuEurPaymentChannel,
  cashLvEurPaymentChannel,
  cashLyLydPaymentChannel,
  cashMaMadPaymentChannel,
  cashMcEurPaymentChannel,
  cashMdMdlPaymentChannel,
  cashMeEurPaymentChannel,
  cashMfEurPaymentChannel,
  cashMgMgaPaymentChannel,
  cashMhUsdPaymentChannel,
  cashMkMkdPaymentChannel,
  cashMlXofPaymentChannel,
  cashMmMmkPaymentChannel,
  cashMnMntPaymentChannel,
  cashMoMopPaymentChannel,
  cashMpUsdPaymentChannel,
  cashMqEurPaymentChannel,
  cashMrMruPaymentChannel,
  cashMsXcdPaymentChannel,
  cashMtEurPaymentChannel,
  cashMuMurPaymentChannel,
  cashMvMvrPaymentChannel,
  cashMwMwkPaymentChannel,
  cashMxMxnPaymentChannel,
  cashMyMyrPaymentChannel,
  cashMzMznPaymentChannel,
  cashNaNadPaymentChannel,
  cashNaZarPaymentChannel,
  cashNcXpfPaymentChannel,
  cashNeXofPaymentChannel,
  cashNfAudPaymentChannel,
  cashNgNgnPaymentChannel,
  cashNiNioPaymentChannel,
  cashNlEurPaymentChannel,
  cashNoNokPaymentChannel,
  cashNpNprPaymentChannel,
  cashNrAudPaymentChannel,
  cashNuNzdPaymentChannel,
  cashNzNzdPaymentChannel,
  cashPaPabPaymentChannel,
  cashPaUsdPaymentChannel,
  cashPePenPaymentChannel,
  cashPfXpfPaymentChannel,
  cashPgPgkPaymentChannel,
  cashPhPhpPaymentChannel,
  cashPkPkrPaymentChannel,
  cashPlPlnPaymentChannel,
  cashPmEurPaymentChannel,
  cashPnNzdPaymentChannel,
  cashPrUsdPaymentChannel,
  cashPtEurPaymentChannel,
  cashPwUsdPaymentChannel,
  cashPyPygPaymentChannel,
  cashReEurPaymentChannel,
  cashRoRonPaymentChannel,
  cashRsRsdPaymentChannel,
  cashRuRubPaymentChannel,
  cashRwRwfPaymentChannel,
  cashSbSbdPaymentChannel,
  cashScScrPaymentChannel,
  cashSdSdgPaymentChannel,
  cashSeSekPaymentChannel,
  cashSgSgdPaymentChannel,
  cashShShpPaymentChannel,
  cashSiEurPaymentChannel,
  cashSjNokPaymentChannel,
  cashSkEurPaymentChannel,
  cashSlSlePaymentChannel,
  cashSmEurPaymentChannel,
  cashSnXofPaymentChannel,
  cashSoSosPaymentChannel,
  cashSoUsdPaymentChannel,
  cashSrSrdPaymentChannel,
  cashSsSspPaymentChannel,
  cashStStnPaymentChannel,
  cashSvUsdPaymentChannel,
  cashSxAngPaymentChannel,
  cashSzSzlPaymentChannel,
  cashSzZarPaymentChannel,
  cashTcUsdPaymentChannel,
  cashTdXafPaymentChannel,
  cashTgXofPaymentChannel,
  cashThThbPaymentChannel,
  cashTjTjsPaymentChannel,
  cashTkNzdPaymentChannel,
  cashTlUsdPaymentChannel,
  cashTmTmtPaymentChannel,
  cashTnTndPaymentChannel,
  cashToTopPaymentChannel,
  cashTtTtdPaymentChannel,
  cashTvAudPaymentChannel,
  cashTwTwdPaymentChannel,
  cashTzTzsPaymentChannel,
  cashUaUahPaymentChannel,
  cashUgUgxPaymentChannel,
  cashUsUsdPaymentChannel,
  cashUyUyuPaymentChannel,
  cashUzUzsPaymentChannel,
  cashVaEurPaymentChannel,
  cashVcXcdPaymentChannel,
  cashVeVesPaymentChannel,
  cashVgUsdPaymentChannel,
  cashViUsdPaymentChannel,
  cashVnVndPaymentChannel,
  cashVuVuvPaymentChannel,
  cashWfXpfPaymentChannel,
  cashWsWstPaymentChannel,
  cashYtEurPaymentChannel,
  cashZaZarPaymentChannel,
  cashZmZmwPaymentChannel,
  cashZwUsdPaymentChannel,
  cashZwZwgPaymentChannel,
  createCashPaymentChannel,
  mpesaPaybillKeKesPaymentChannel,
  mpesaPhoneKeKesPaymentChannel,
  mpesaPochiKeKesPaymentChannel,
  mpesaTillKeKesPaymentChannel,
  payshapAccountZaZarPaymentChannel,
  payshapShapidZaZarPaymentChannel,
  pesalinkAccountKeKesPaymentChannel,
  telebirrPhoneEtEtbPaymentChannel,
  tnmMpambaMerchantMwMwkPaymentChannel,
  tnmMpambaMwMwkPaymentChannel,
} from "./channels/index.js";

export function createPaymentChannelRegistry(
  schemas: readonly PaymentChannelSchema[] = builtinPaymentChannels,
): Map<PaymentChannelId, PaymentChannelSchema> {
  return buildPaymentChannelRegistry(schemas);
}
